### ISSUE TITLE
选课达18学时，课程无法替换

### ISSUE THREAD

**Issue by Rat-racer** [114DoctorGroup/epc-spider#1]
若已获得学时为18学时，且已经预约了下一次的课程，
那么可预约学时为2学时，
运行脚本时，若遇到可选课程，选课时系统会提示无法选课，因为超过了20学时。

导致无法替换课程。

可以判断一下，如果当前用户已获得学时为18学时，且已经预约了下一次的课程、
且enable.replace" : true,的情况下。

应该先退课，再选课。

**Comment by ypluo** [comment]
有两种解决方案：
1, 注释掉选课主循环里面 available_hours大于2直接选课的代码
2. 更改check_study_hour()中获得available_hours的代码，直接让它在20学分时返回0可用学时

**Comment by songchaow** [comment]
谢谢反馈，应该已经修好了
